"""The boundary guardrails: one RED case per rule, and the repository itself (task `A22`).

Each rule is exercised on a throwaway repository that contains exactly the failure it is
meant to catch — no rule is trusted because it looks right — and the last test runs the
whole checker against this repository, which is the guardrail that has to keep holding.
"""

import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import check_boundaries  # noqa: E402


class BoundaryRuleCase(unittest.TestCase):
    """A throwaway repository the rule under test can fail in."""

    def setUp(self) -> None:
        self._temporary = tempfile.TemporaryDirectory()
        self.root = Path(self._temporary.name)
        subprocess.run(["git", "init", "-q"], cwd=self.root, check=True)

    def tearDown(self) -> None:
        self._temporary.cleanup()

    def write(self, relative: str, content: str) -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    def track_everything(self) -> None:
        subprocess.run(["git", "add", "-A", "-f"], cwd=self.root, check=True)

    def rules_fired(self) -> set[str]:
        self.track_everything()
        return {finding.rule for finding in check_boundaries.findings_for(self.root)}


class VendoredMaterialTest(BoundaryRuleCase):
    def test_a_committed_aar_is_a_finding(self) -> None:
        self.write("engine/maven/dev/ironjanowar/fretboard-engine/0.8.0/fretboard-engine-0.8.0.aar", "binary")

        self.assertIn("vendored-material", self.rules_fired())

    def test_a_committed_keystore_is_a_finding(self) -> None:
        self.write("keystore.properties", "storeFile=release.jks")

        fired = self.rules_fired()

        self.assertIn("vendored-material", fired)

    def test_nothing_binary_is_reported_in_a_clean_repository(self) -> None:
        self.write("app/src/main/java/dev/ironjanowar/fretboard/MainActivity.kt", "package dev.ironjanowar.fretboard\n")
        self.write("core-release.lock.json", json.dumps({"artifact_version": "0.8.0", "sha256": "a" * 64, "source_commit": "b" * 40}))
        self.write("gradle/wrapper/gradle-wrapper.jar", "the wrapper, committed on purpose")

        self.assertEqual(set(), self.rules_fired())

    def test_the_gradle_wrapper_is_not_a_finding(self) -> None:
        # The one binary this repository commits deliberately: it is the tool that fetches
        # everything else, and a guardrail that refuses it would be wrong.
        self.write("core-release.lock.json", json.dumps({"artifact_version": "0.8.0", "sha256": "a" * 64, "source_commit": "b" * 40}))
        self.write("gradle/wrapper/gradle-wrapper.jar", "the wrapper, committed on purpose")

        self.assertNotIn("vendored-material", self.rules_fired())


class ImmutablePinTest(BoundaryRuleCase):
    def test_a_mutable_version_is_a_finding(self) -> None:
        self.write("core-release.lock.json", json.dumps({"artifact_version": "0.8.0-SNAPSHOT", "sha256": "a" * 64, "source_commit": "b" * 40}))

        self.assertIn("immutable-pin", self.rules_fired())

    def test_a_short_digest_is_a_finding(self) -> None:
        self.write("core-release.lock.json", json.dumps({"artifact_version": "0.8.0", "sha256": "abc", "source_commit": "b" * 40}))

        self.assertIn("immutable-pin", self.rules_fired())

    def test_a_short_source_commit_is_a_finding(self) -> None:
        # This is the mistake that reached a pull request: a commit written from its short
        # form instead of read from the artifact.
        self.write("core-release.lock.json", json.dumps({"artifact_version": "0.8.0", "sha256": "a" * 64, "source_commit": "8124e1f"}))

        self.assertIn("immutable-pin", self.rules_fired())


class PackageTest(BoundaryRuleCase):
    def test_a_package_that_does_not_match_its_directory_is_a_finding(self) -> None:
        self.write("app/src/main/java/dev/ironjanowar/fretboard/ui/Thing.kt", "package dev.ironjanowar.wrong\n")

        self.assertIn("package", self.rules_fired())


class GeneratedSourceTest(BoundaryRuleCase):
    def test_a_committed_binding_is_a_finding(self) -> None:
        self.write("app/src/main/java/dev/ironjanowar/fretboard/core/Fretboard.kt", "// This file was autogenerated by uniffi\npackage dev.ironjanowar.fretboard.core\n")

        self.assertIn("generated-source", self.rules_fired())


class NoteTableTest(BoundaryRuleCase):
    def test_a_note_table_in_kotlin_is_a_finding(self) -> None:
        self.write(
            "app/src/main/java/dev/ironjanowar/fretboard/ui/Notes.kt",
            'package dev.ironjanowar.fretboard.ui\n\nval names = listOf("C#", "D#", "F#", "G#", "A#", "Db", "Eb", "Gb", "Ab")\n',
        )

        self.assertIn("kotlin-music-table", self.rules_fired())


class AppPackagingContractTest(unittest.TestCase):
    def test_application_declares_exactly_the_supported_abis(self) -> None:
        repository = Path(__file__).resolve().parent.parent.parent
        build_script = (repository / "app/build.gradle.kts").read_text()
        ndk_block = re.search(r"\bndk\s*\{(?P<body>[^{}]*)\}", build_script)

        self.assertIsNotNone(ndk_block, "app/build.gradle.kts must declare an ndk block")
        assert ndk_block is not None
        self.assertIn("abiFilters", ndk_block.group("body"))
        declared_abis = re.findall(r'"([^"]+)"', ndk_block.group("body"))

        self.assertCountEqual(["arm64-v8a", "x86_64"], declared_abis)


class TheRepositoryItselfTest(unittest.TestCase):
    def test_this_repository_has_no_boundary_finding(self) -> None:
        # The guardrail that has to keep holding: if a rule starts failing on the real
        # repository, either the repository changed or the rule is wrong.
        findings = check_boundaries.findings_for(Path(__file__).resolve().parent.parent.parent)

        self.assertEqual([], [str(finding) for finding in findings])


if __name__ == "__main__":
    unittest.main()
