#!/usr/bin/env python3
"""Boundary guardrails for this repository (task `A22`).

These are *guardrails plus review*, not proof: a static rule can say that no Kotlin file
contains a note table, and it cannot say that an arbitrary Kotlin file contains no musical
logic. They exist to catch the failures that are otherwise invisible in a diff, and every
one of them has a RED case in `scripts/tests/test_check_boundaries.py`.

Run: `python3 scripts/check_boundaries.py` from the repository root.

Exit code 0 when every rule holds, 1 with one line per finding.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The application's own package, and the one directory that may declare it.
APP_PACKAGE = "dev.ironjanowar.fretboard"
APP_SOURCES = Path("app/src")

# Binary or secret material that must never be committed: the engine arrives from its
# GitHub Release, and the signing material lives outside the repository.
FORBIDDEN_SUFFIXES = (".aar", ".apk", ".so", ".klib", ".jar", ".jks", ".keystore")
FORBIDDEN_NAMES = ("keystore.properties",)

# A version that can resolve to something else between two builds.
MUTABLE_VERSION = re.compile(r"(\+|SNAPSHOT|LATEST|latest|\*\b)")

# The Gradle wrapper is the one binary this repository commits on purpose: it is the build
# tool that fetches everything else, and refusing it would make the guardrail wrong.
ALLOWED_BINARIES = ("gradle/wrapper/gradle-wrapper.jar",)

# Generated UniFFI output is a build product: it is never committed, and its place is the
# AAR the preparation script installs.
GENERATED_MARKERS = (
    "This file was autogenerated by uniffi",
    "Generated by uniffi",
    "AUTOGENERATED by uniffi",
)

# The twelve pitch classes as Kotlin string literals in one file is a note table, and a note
# table in Kotlin is a second music implementation. A single note name in a message is not.
PITCH_CLASSES = ('"C#"', '"D#"', '"F#"', '"G#"', '"A#"', '"Db"', '"Eb"', '"Gb"', '"Ab"', '"Bb"')
NOTE_TABLE_THRESHOLD = 8


@dataclass(frozen=True)
class Finding:
    """One rule that does not hold, with the path that proves it."""

    rule: str
    path: str
    detail: str

    def __str__(self) -> str:
        return f"{self.rule}: {self.path}: {self.detail}"


def tracked_files(root: Path = ROOT) -> list[str]:
    """Every file git tracks, so ignored build output is not a finding."""
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def check_no_vendored_material(files: list[str], root: Path = ROOT) -> list[Finding]:
    findings = []
    for name in files:
        path = Path(name)
        if name in ALLOWED_BINARIES:
            continue
        if path.name in FORBIDDEN_NAMES or path.suffix in FORBIDDEN_SUFFIXES:
            findings.append(
                Finding(
                    "vendored-material",
                    name,
                    "committed binary or signing material: the engine comes from its release "
                    "and the keystore lives outside the repository",
                )
            )
    return findings


def check_lock_is_immutable(root: Path = ROOT) -> list[Finding]:
    lock = root / "core-release.lock.json"
    if not lock.exists():
        return [Finding("immutable-pin", "core-release.lock.json", "the release lock is missing")]

    data = json.loads(lock.read_text())
    findings = []

    version = str(data.get("artifact_version", ""))
    if not version or MUTABLE_VERSION.search(version):
        findings.append(
            Finding("immutable-pin", "core-release.lock.json", f"mutable artifact version: {version!r}")
        )

    digest = str(data.get("sha256", ""))
    if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
        findings.append(
            Finding("immutable-pin", "core-release.lock.json", f"not a SHA-256 digest: {digest!r}")
        )

    source_commit = str(data.get("source_commit", ""))
    if len(source_commit) != 40 or any(c not in "0123456789abcdef" for c in source_commit):
        findings.append(
            Finding(
                "immutable-pin",
                "core-release.lock.json",
                f"not a full commit: {source_commit!r}",
            )
        )
    return findings


def check_package_matches_directory(files: list[str], root: Path = ROOT) -> list[Finding]:
    findings = []
    for name in files:
        if not name.startswith(str(APP_SOURCES)) or not name.endswith(".kt"):
            continue
        source = (root / name).read_text()
        declared = re.search(r"^package\s+([\w.]+)", source, re.MULTILINE)
        if declared is None:
            findings.append(Finding("package", name, "no package declaration"))
            continue
        package = declared.group(1)
        # The expected package is the application's own, plus the directories *below* it:
        # a file in `.../dev/ironjanowar/fretboard/links/` declares `.links`, and a file in
        # the package's own directory declares exactly `APP_PACKAGE`.
        marker = APP_PACKAGE.replace(".", "/")
        split = str(Path(name).parent).split(marker, 1)
        suffix = split[1].strip("/") if len(split) > 1 else ""
        expected = APP_PACKAGE if suffix == "" else f"{APP_PACKAGE}.{suffix.replace('/', '.')}"
        if package != expected:
            findings.append(
                Finding("package", name, f"declares {package}, its directory is {expected}")
            )
    return findings


def check_no_generated_sources(files: list[str], root: Path = ROOT) -> list[Finding]:
    findings = []
    for name in files:
        if not name.endswith(".kt"):
            continue
        source = (root / name).read_text()
        if any(marker in source for marker in GENERATED_MARKERS):
            findings.append(
                Finding("generated-source", name, "generated bindings are a build product, not a source file")
            )
    return findings


def check_no_note_tables(files: list[str], root: Path = ROOT) -> list[Finding]:
    findings = []
    for name in files:
        if not name.startswith(str(APP_SOURCES)) or not name.endswith(".kt"):
            continue
        source = (root / name).read_text()
        present = sum(1 for literal in PITCH_CLASSES if literal in source)
        if present >= NOTE_TABLE_THRESHOLD:
            findings.append(
                Finding(
                    "kotlin-music-table",
                    name,
                    f"carries {present} pitch-class literals: a note table belongs to the engine",
                )
            )
    return findings


RULES = (
    check_no_vendored_material,
    check_lock_is_immutable,
    check_package_matches_directory,
    check_no_generated_sources,
    check_no_note_tables,
)


def findings_for(root: Path = ROOT) -> list[Finding]:
    """Every finding under `root`, which the tests point at their own fixtures."""
    files = tracked_files(root)
    findings: list[Finding] = []
    for rule in RULES:
        if rule in (check_no_vendored_material, check_package_matches_directory,
                    check_no_generated_sources, check_no_note_tables):
            findings.extend(rule(files, root))
        else:
            findings.extend(rule(root))
    return findings


def main() -> int:
    findings = findings_for()
    for finding in findings:
        print(finding)
    if findings:
        print(f"{len(findings)} boundary finding(s)")
        return 1
    print("boundaries hold")
    return 0


if __name__ == "__main__":
    sys.exit(main())
